//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists in the system.
        /// </summary>
        internal static string EN_CodeExist {
            get {
                return ResourceManager.GetString("EN_CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentCode.
        /// </summary>
        internal static string EN_DepartmentCode {
            get {
                return ResourceManager.GetString("EN_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentId.
        /// </summary>
        internal static string EN_DepartmentId {
            get {
                return ResourceManager.GetString("EN_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentName.
        /// </summary>
        internal static string EN_DepartmentName {
            get {
                return ResourceManager.GetString("EN_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EN_Email {
            get {
                return ResourceManager.GetString("EN_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode.
        /// </summary>
        internal static string EN_EmployeeCode {
            get {
                return ResourceManager.GetString("EN_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not allowed to be empty.
        /// </summary>
        internal static string EN_EmptyCheck {
            get {
                return ResourceManager.GetString("EN_EmptyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID does not exist.
        /// </summary>
        internal static string EN_EmptyCheckId {
            get {
                return ResourceManager.GetString("EN_EmptyCheckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID already exists in the system.
        /// </summary>
        internal static string EN_EmptyCheckIdExist {
            get {
                return ResourceManager.GetString("EN_EmptyCheckIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error, please contact MISA.
        /// </summary>
        internal static string EN_ErrorSystem {
            get {
                return ResourceManager.GetString("EN_ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string EN_FileExist {
            get {
                return ResourceManager.GetString("EN_FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file format.
        /// </summary>
        internal static string EN_FileNotFormat {
            get {
                return ResourceManager.GetString("EN_FileNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string EN_FullName {
            get {
                return ResourceManager.GetString("EN_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input data.
        /// </summary>
        internal static string EN_InvalidInput {
            get {
                return ResourceManager.GetString("EN_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionsName.
        /// </summary>
        internal static string EN_PositionsName {
            get {
                return ResourceManager.GetString("EN_PositionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalidate.
        /// </summary>
        internal static string EN_VaildateEmail {
            get {
                return ResourceManager.GetString("EN_VaildateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống.
        /// </summary>
        internal static string VN_CodeExist {
            get {
                return ResourceManager.GetString("VN_CodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban.
        /// </summary>
        internal static string VN_DepartmentCode {
            get {
                return ResourceManager.GetString("VN_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khóa chính đối tượng phòng ban.
        /// </summary>
        internal static string VN_DepartmentId {
            get {
                return ResourceManager.GetString("VN_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng Ban.
        /// </summary>
        internal static string VN_DepartmentName {
            get {
                return ResourceManager.GetString("VN_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string VN_Email {
            get {
                return ResourceManager.GetString("VN_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        internal static string VN_EmployeeCode {
            get {
                return ResourceManager.GetString("VN_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép để trống.
        /// </summary>
        internal static string VN_EmptyCheck {
            get {
                return ResourceManager.GetString("VN_EmptyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không tồn tại.
        /// </summary>
        internal static string VN_EmptyCheckId {
            get {
                return ResourceManager.GetString("VN_EmptyCheckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đã tồn tại trong hệ thống.
        /// </summary>
        internal static string VN_EmptyCheckIdExist {
            get {
                return ResourceManager.GetString("VN_EmptyCheckIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        internal static string VN_ErrorSystem {
            get {
                return ResourceManager.GetString("VN_ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp không tồn tại.
        /// </summary>
        internal static string VN_FileExist {
            get {
                return ResourceManager.GetString("VN_FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp không đúng định dạng.
        /// </summary>
        internal static string VN_FileNotFormat {
            get {
                return ResourceManager.GetString("VN_FileNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        internal static string VN_FullName {
            get {
                return ResourceManager.GetString("VN_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        internal static string VN_InvalidInput {
            get {
                return ResourceManager.GetString("VN_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí chức vụ .
        /// </summary>
        internal static string VN_PositionsName {
            get {
                return ResourceManager.GetString("VN_PositionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không đúng định dạng.
        /// </summary>
        internal static string VN_VaildateEmail {
            get {
                return ResourceManager.GetString("VN_VaildateEmail", resourceCulture);
            }
        }
    }
}
